version: '3'
services:
  mariadb:
    image: registry.cn-hangzhou.aliyuncs.com/prince/stretch-mariadb:10.3
    container_name: mariadb
    hostname: mariadb
    network_mode: "host"
    logging:
      options:
        max-size: 512m
    restart:
     on-failure:3
    privileged: "true"
    tty: "true"
    ulimits:
     core: 0
    environment :
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - "/mnt:/mnt"
      - "/data:/data"
      - "/data/share/mysql-conf.d:/etc/mysql/conf.d"
  swoole:
    image: registry.cn-hangzhou.aliyuncs.com/prince/alpine-php:7.3.3-cli-swoole4.3.1
    container_name: swoole
    hostname: swoole
    network_mode: "host"
    logging:
      options:
        max-size: 512m
    restart: always
    privileged: "true"
    tty: "true"
    #ulimits:
    # core: 0
    volumes:
      - "/mnt:/mnt"
      - "/data:/data"
    #command: []
